### ISSUE TITLE
How to add turbo button support?

### ISSUE THREAD

**Issue by sharma-abhishek-it** [OpenEmu/FCEU-Core#1]
Hey guys,

I am using OpenEMU and just love it. The one thing missing is turbo button support. I believe this has two parts:
1. You need to add turbo button mapping in UI
2. The FCEU core must understand that mapping so that those buttons can be emulated

So I believe the harder task is no. 2, so may be we can begin with that first?

So if anyone can guide me how to do that, I would love to add these support myself. It will be a fun task to do :thumbsup:

**Comment by FeindFire** [comment]
It's a feature that matters for a lot of old shooters. they don't all autofire when you hold the fire button, so a turbo feature is practically a must for a lover of shooters (like me). This thread is almost 4 years old, but there are closed threads from just the last few months of people still asking for the feature, they still don't have the feature. I don't see how it would be hard to integrate turbo buttons into the existing keybinding menu. Just add a third section to the keybinding.

Having spent some time complaining, I want to put it out there that this is my favorite app on my Mac, and I'm incredibly grateful to the developer for the unbeatably convenient emulation solution
