### ISSUE TITLE
Slow NES games

### ISSUE THREAD

**Issue by Shrapnel21** [OpenEmu/FCEU-Core#10]
Using Openemu 2.0.8 (both normal and experimental) on my late 2013 27" iMac (3,4GHz Core i5 and 16GB RAM) I noticed NES games are really slow when using the FCEU core. Didn't realize this until a while ago, when I saw a cool guy on Twitch speedrunning Batman on the NES and noticed the game was a lot faster than when I played it on my Mac with Openemu. Did this ever happen to anybody else? Are more details needed?

**Comment by clobber** [comment]
Nope, both Nestopia and FCEUX cores run at the same speed. You are either noticing PAL vs NTSC differences in speed or experiencing the bug on macOS 10.14 where a zoomed/full screen gameplay window can have bad performance.

**Comment by Shrapnel21** [comment]
Windowed mode, not zoomed and slow with the NTSC version as well. I'll dig deeper, but something's not going well.

**Comment by Shrapnel21** [comment]
Windowed mode, not zoomed and slow with the NTSC version as well. I'll dig deeper, but something's not going well. Forgot to mention the same ROMs are running way faster on RetroArch with the FCE core.

**Comment by clobber** [comment]
Then use that? Don't know what to tell you -- both of our NES core plugins run at the same speed here. There is some other issue going on if you are not experiencing that.

**Comment by Shrapnel21** [comment]
I wasn't actually implying there's something wrong with Openemu, I'm pretty sure there's some weird issue on my side and I was asking for help/suggestions. But yes, switching over to RetroArch will definitely be quicker, that's sound advice from you. Thanks and happy Easter Monday!
