### ISSUE TITLE
NES Zapper emulation

### ISSUE THREAD

**Issue by illando** [OpenEmu/FCEU-Core#4]
I check on FCEU sites and I know it's able to emulate light guns using the mouse cursor.
I don't know if it's possible but ...could be awesome to have this function in Open Emu, to play great games like Duck Hunt. Maybe also enable the wiimote to work as NES Zapper.
Thanks.

**Comment by clobber** [comment]
e9c3efd23ff5a4c343e74afe4209c874f0a2259a & 972d43dc053499ddf7e87467637b7cc91c10f7d5
