### ISSUE TITLE
CoolBoy mapper support

### ISSUE THREAD

**Issue by belovo** [OpenEmu/FCEU-Core#5]
Can someone please add additional mappers support? Here is a Windows source with all the new mappers http://sourceforge.net/p/fceumm/code/commit_browser. I was trying to compile it myself but I'm not skilled enough to do this, please help!

**Comment by clobber** [comment]
Sorry, no. We generally do not modify the emulators and our FCEU port is of FCEUX, not FCEUmm.

I'd recommend asking upstream FCEUX for additional mapper support and then that will make it our way as we update.
