### ISSUE TITLE
Compilation error: "Ordered comparison between pointer and zero ('char *' and 'int')"

### ISSUE THREAD

**Issue by spamguy** [OpenEmu/FCEU-Core#7]
For many months I've been unable to build OpenEmu and its cores. It hits a snag building the FCEU portion. Within Terminal, the output is
```
The following build commands failed:
	CompileC /Users/spamguy/src/OpenEmu/DerivedData/Build/Intermediates/FCEU.build/Release/FCEU.build/Objects-normal/x86_64/cheat.o src/cheat.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
```

Within Xcode, the error is a little more clear.
```
/Users/spamguy/src/OpenEmu/FCEU/src/cheat.cpp:219:30: Ordered comparison between pointer and zero ('char *' and 'int')
```

I understand its complaint, but this hasn't been addressed on the FCEU repository itself, so the problem must be on my side. What is escalating this from a warning to an error?

**Comment by mrvacbob** [comment]
What are your OS and Xcode versions?

**Comment by spamguy** [comment]
Running 10.13.1, Xcode 9.2, although I recall this error going back to 10.12.x and Xcode 8.x.

**Comment by clobber** [comment]
https://github.com/OpenEmu/FCEU-Core/commit/10e4d8fd3844a89eec2eccd3337d3e383141cccf
