### ISSUE TITLE
Additional cheat code formats

### ISSUE THREAD

**Issue by EmulatorAddict** [OpenEmu/FCEU-Core#9]
I've been using OpenEMU since I purchased my Mac three years ago. Cheat codes work fine for all systems that utilize them, with the exception of any and all AR/FCE Ultra Debug NES codes (format XXXX:YY). They have never worked, and FCEU is the default core on my setup.

MacOS: Mojave 10.14.1
OpenEMU version: 2.0.8 (installed today, 12/4/2018)

Thanks.

**Comment by clobber** [comment]
It's *OpenEmu*, Emu as in Emulator. No acronym.

Anyway, Game Genie is the only supported cheat code format in the NES core plugins at the moment.

**Comment by EmulatorAddict** [comment]
Ah, then may I suggest that it be removed from the Cheat Codes portion of the User's Guide?

**Comment by clobber** [comment]
Much better to just add support for the missing format.

Added in https://github.com/OpenEmu/Nestopia-Core/commit/bae9392405612ac3fe48ed0334f7c94d199911f1 && https://github.com/OpenEmu/FCEU-Core/commit/c1271716eb742dee25a7e690b6a4f245ea2ee436

Restart the app and updated Nestopia and FCEUX core plugins will automatically download and install. You can verify you have the new versions by going to OpenEmu > Preferences > Cores and looking for Nestopia 1.49.0.1 and FCEU 2.2.3.2

Some notes
* A good resource for finding cheat codes is [GameHacking.org](http://gamehacking.org).
* These formats can easily be converted (http://www.chrismcovell.com/CheatConverter.html, https://satoshinm.github.io/nescode/), so one doesn't have to rely on Address?Compare:Value.
* The obscure "Pro Action Rocky" format doesn't work correctly in FCEUX, but nobody uses it anyway.
* It is recommended to use Nestopia as the default NES core plugin as it's synced up with the latest stable release from [upstream](https://github.com/0ldsk00l/nestopia) and probably has less mapper and cheat code bugs than FCEUX at this point. FCEUX hasn't had a new stable release in over two years.

**Comment by EmulatorAddict** [comment]
Thanks very much, all code formats appear to be working! Thanks again!
